export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const INCREMENT_TO_CART = "INCREMENT_TO_CART";
export const DECREMENT_TO_CART = "DECREMENT_TO_CART";